name: .NET

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
env:
  AZURE_WEBAPP_NAME: ira-api

jobs:
  dotnetapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Restore dependencies
        run: cd IRAAPI && dotnet restore
      - name: Build
        run: cd IRAAPI &&  dotnet build --no-restore
      - name: Test
        run: cd IRAAPI &&  dotnet test --no-build --verbosity normal
      - name: dotnet publish
        run: |
        dotnet publish -c Release -o dotnetcorewebapp
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: <publishData><publishProfile profileName="ira-api - Web Deploy" publishMethod="MSDeploy" publishUrl="ira-api.scm.azurewebsites.net:443" msdeploySite="ira-api" userName="$ira-api" userPWD="5yfAadBupmuxzetwAsRy2knoffbHnH03uwj3swa4QDtqoJmT1RazJgBswye9" destinationAppUrl="http://ira-api.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="ira-api - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-cbr20-003.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="ira-api\$ira-api" userPWD="5yfAadBupmuxzetwAsRy2knoffbHnH03uwj3swa4QDtqoJmT1RazJgBswye9" destinationAppUrl="http://ira-api.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="ira-api - Zip Deploy" publishMethod="ZipDeploy" publishUrl="ira-api.scm.azurewebsites.net:443" userName="$ira-api" userPWD="5yfAadBupmuxzetwAsRy2knoffbHnH03uwj3swa4QDtqoJmT1RazJgBswye9" destinationAppUrl="http://ira-api.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="ira-api - ReadOnly - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-cbr20-003dr.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="ira-api\$ira-api" userPWD="5yfAadBupmuxzetwAsRy2knoffbHnH03uwj3swa4QDtqoJmT1RazJgBswye9" destinationAppUrl="http://ira-api.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
          package: './dotnetcorewebapp'

  reactapp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup node env
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Restore dependencies
        run: cd intelligent_remote_academia-frontend && npm install
      - name: Build
        run: cd intelligent_remote_academia-frontend && npm build
